# Site settings
title: Zetta EIRL
tag_text: Zetta EIRL
description: Zetta EIRL es una empresa de servicios informáticos, desarrollo Web y sistemas empresariales.

# Build settings
markdown: kramdown

google_analytics: true

exclude: ["README.md"]
